{
 "title": "Mikrotik MKTXP Exporter",
 "description": "Mikrotik MKTXP Exporter metrics",
 "tags": [
  "mikrotik",
  "dashboard",
  "mktxp"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(mktxp_system_identity_info, routerboard_address)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Identity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_system_identity_info{routerboard_address=\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "System uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mktxp_system_uptime{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System uptime" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "expr": "(1 - mktxp_system_free_memory{routerboard_address=\"$node\"} / mktxp_system_total_memory{routerboard_address=\"$node\"})*100",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Used memory" },
     "legendFormat": "Used RAM Memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "mktxp_system_cpu_load{routerboard_address=\"$node\"}",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "(1 - mktxp_system_free_hdd_space{routerboard_address=\"$node\"} / mktxp_system_total_hdd_space{routerboard_address=\"$node\"})*100",
     "legendFormat": "HDD Utilization"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "expr": "mktxp_system_cpu_load{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "CPU 1 load" },
     "legendFormat": "{{cpu}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "HDD Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Memory" },
     "expr": "mktxp_system_total_hdd_space{routerboard_address=\"$node\"} - mktxp_system_free_hdd_space{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Used memory" },
     "legendFormat": "Used memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "Memory" },
     "expr": "mktxp_system_total_hdd_space{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Total memory" },
     "legendFormat": "Total memory",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Routerboard HW",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_system_uptime{routerboard_address=\"$node\"}",
     "legendFormat": "{{board_name}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mktxp_system_routerboard_temperature{routerboard_address=\"$node\"}  "
    }
   ]
  },
  {
   "title": "System version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mktxp_system_uptime{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System version and hw" },
     "legendFormat": "{{version}} ",
     "mode": 2,
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mktxp_system_routerboard_voltage{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System version and hw" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Interface traffic ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_interface_rx_byte_total{routerboard_address=\"$node\"}[15s]) * 8",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "In | {{ name }}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_interface_tx_byte_total{routerboard_address=\"$node\"}[15s]) * 8",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Outgoing traffic on interface ether1-gateway"
     },
     "legendFormat": "Out | {{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "DHCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "DHCP Leases by Server",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mktxp_dhcp_lease_active_count{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ server }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "DHCP Leases",
   "type": "table",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 17 },
   "targets": [
    {
     "expr": "mktxp_dhcp_lease_info{routerboard_address=\"$node\"}"
    }
   ]
  },
  {
   "title": "Total DHCP Leases",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "sum(mktxp_dhcp_lease_active_count{routerboard_address=\"$node\"})",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "In - {{ server }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Total Routes",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_routes_total_routes{routerboard_address=\"$node\"}"
    }
   ]
  },
  {
   "title": "Routes per protocol",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mktxp_routes_protocol_count{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "/errors on interface/" },
     "legendFormat": "{{protocol}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Ethernet Ports: Full Duplex",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_interface_full_duplex{routerboard_address=\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Interface Errors",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mktxp_interface_rx_error_total{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "/errors on interface/" },
     "legendFormat": "In Errors | {{name}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "mktxp_interface_tx_error_total{routerboard_address=\"$node\"}",
     "legendFormat": "Out Errors | {{name}}"
    }
   ]
  },
  {
   "title": "Ethernet Ports: Status",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mktxp_interface_status{routerboard_address=\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Rates",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "mktxp_interface_rate{routerboard_address=\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "POE",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "mktxp_poe_info{routerboard_address=\"$node\"}"
    }
   ]
  },
  { "title": "Firewall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Logged Firewall Rules Traffic ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_firewall_filter_total{routerboard_address=\"$node\", log=\"1\"}[4m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Logged Raw Firewall Rules Traffic ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_firewall_raw_total{routerboard_address=\"$node\", log=\"1\"}[4m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Firewall Rules Traffic ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_firewall_filter_total{routerboard_address=\"$node\"}[4m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Raw Firewall Rules Traffic ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_firewall_raw_total{routerboard_address=\"$node\"}[4m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Internet Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    { "expr": "mktxp_internet_bandwidth", "legendFormat": "{{direction}}" }
   ]
  },
  {
   "title": "Internet Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "mktxp_internet_latency", "legendFormat": "latency" }
   ]
  },
  { "title": "Netwatch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Status over time",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "max_over_time(mktxp_netwatch_status{routerboard_address=\"$node\"}[1m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Netwatch Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "mktxp_netwatch_info{routerboard_address=\"$node\"}"
    }
   ]
  },
  { "title": "Wireless", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Noise Floor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "expr": "mktxp_wlan_noise_floor{routerboard_address=\"$node\"}",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Overall Tx CCQ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mktxp_wlan_overall_tx_ccq{routerboard_address=\"$node\"}",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Client Devices",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "mktxp_wlan_clients_devices_info{routerboard_address=\"$node\"}"
    }
   ]
  },
  {
   "title": "Number of clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mktxp_wlan_registered_clients{routerboard_address=\"$node\"}",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "WLAN Clients Tx CCQ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mktxp_wlan_clients_tx_ccq{routerboard_address=\"$node\"}",
     "legendFormat": "{{dhcp_name}}"
    }
   ]
  },
  {
   "title": "Clients Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_wlan_clients_tx_bytes_total{routerboard_address=\"$node\"}[4m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "In - {{ dhcp_name }}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_wlan_clients_rx_bytes_total{routerboard_address=\"$node\"}[4m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Outgoing traffic on interface ether1-gateway"
     },
     "legendFormat": "Out - {{ dhcp_name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Clients Signal Strength",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mktxp_wlan_clients_signal_strength{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ dhcp_name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Clients  Signal-to-Noise ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mktxp_wlan_clients_signal_to_noise{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ dhcp_name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "CAPsMAN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Remote Caps",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mktxp_capsman_remote_caps_info{routerboard_address=\"$node\"}",
     "legendFormat": "{{identity}}"
    }
   ]
  },
  {
   "title": "CAPsMAN Clients",
   "type": "table",
   "gridPos": { "h": 15, "w": 18, "x": 6, "y": 113 },
   "targets": [
    {
     "expr": "mktxp_capsman_clients_devices_info{routerboard_address=\"$node\"}"
    }
   ]
  },
  {
   "title": "CAPsMAN Registrations",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 119 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mktxp_capsman_registrations_count{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ interface }}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "sum(mktxp_capsman_registrations_count{routerboard_address=\"$node\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Registered Client Signal Strength",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mktxp_capsman_clients_signal_strength{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ dhcp_name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CAPsMan Clients Signal Strength",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mktxp_capsman_clients_signal_strength{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ dhcp_name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CAPsMAN Clients Traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_capsman_clients_tx_bytes_total{routerboard_address=\"$node\"}[15s]) * 8",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "In | {{ dhcp_name }}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_capsman_clients_rx_bytes_total{routerboard_address=\"$node\"}[15s]) * 8",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Outgoing traffic on interface ether1-gateway"
     },
     "legendFormat": "Out | {{ dhcp_name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "MKTXP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } },
  {
   "title": "MKTXP Collection Times",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_collection_time_total{routerboard_address=\"$node\"}[4m])  ",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "MKTXP Collection Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 148 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_collection_time_total{routerboard_address=\"$node\"}[4m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "sum(rate(mktxp_collection_time_total{routerboard_address=\"$node\"}[4m]))",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}